# Generated by Django 4.2.29 on 2026-04-04 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concierto',
            name='hora',
        ),
    ]
