# Generated by Django 4.2.29 on 2026-04-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_hora_concierto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=300, verbose_name='Pregunta')),
                ('respuesta', models.TextField(verbose_name='Respuesta')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente',
                'verbose_name_plural': 'Preguntas Frecuentes',
                'ordering': ['orden'],
            },
        ),
    ]
