# Generated by Django 4.2.29 on 2026-04-02 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='foto',
        ),
    ]
