# Generated by Django 4.2.29 on 2026-04-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_remove_unique_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='precio_ida',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Precio Solo Ida (CLP)'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='precio_vuelta',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Precio Solo Vuelta (CLP)'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Precio Ida y Vuelta (CLP)'),
        ),
    ]
