# Generated by Django 4.2.29 on 2026-04-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_precio_ida_vuelta'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='tipo_pasaje',
            field=models.CharField(choices=[('ida_vuelta', 'Ida y Vuelta'), ('solo_ida', 'Solo Ida'), ('solo_vuelta', 'Solo Vuelta')], default='ida_vuelta', max_length=20, verbose_name='Tipo de pasaje'),
        ),
    ]
