# Generated by Django 4.2.29 on 2026-04-03 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_tipo_pasaje_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=200, verbose_name='Punto de Origen')),
                ('destino', models.CharField(max_length=200, verbose_name='Destino')),
                ('fecha_salida', models.DateTimeField(verbose_name='Fecha y Hora de Salida')),
                ('fecha_regreso', models.DateTimeField(verbose_name='Fecha y Hora de Regreso')),
                ('cupos_totales', models.PositiveIntegerField(verbose_name='Cupos Totales')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='reservas.viaje', verbose_name='Viaje')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['fecha_salida'],
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='reservas.horarioviaje', verbose_name='Horario'),
        ),
    ]
