# Generated by Django 4.2.29 on 2026-04-03 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_horario_viaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarioviaje',
            name='fecha_regreso',
        ),
    ]
