# Generated by Django 4.2.29 on 2026-04-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_remove_fecha_regreso_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='fecha_salida',
            field=models.DateField(verbose_name='Fecha de Salida'),
        ),
    ]
