# Generated by Django 4.2.29 on 2026-04-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_viaje_fecha_salida_datefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='precio_ida',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='precio_vuelta',
        ),
        migrations.AddField(
            model_name='horarioviaje',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Precio Ida y Vuelta (CLP)'),
        ),
        migrations.AddField(
            model_name='horarioviaje',
            name='precio_ida',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Precio Solo Ida (CLP)'),
        ),
        migrations.AddField(
            model_name='horarioviaje',
            name='precio_vuelta',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Precio Solo Vuelta (CLP)'),
        ),
    ]
