# Generated by Django 4.2.29 on 2026-04-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_precios_a_horario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarioviaje',
            options={'ordering': ['hora_salida'], 'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
        migrations.RemoveField(
            model_name='horarioviaje',
            name='fecha_salida',
        ),
        migrations.AddField(
            model_name='horarioviaje',
            name='hora_salida',
            field=models.TimeField(default='00:00', verbose_name='Hora de Salida'),
        ),
    ]
