# Generated by Django 4.2.29 on 2026-04-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_horario_hora_salida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='fecha_regreso',
        ),
        migrations.AlterField(
            model_name='horarioviaje',
            name='hora_salida',
            field=models.TimeField(verbose_name='Hora de Salida'),
        ),
    ]
