# Generated by Django 4.2.29 on 2026-04-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_remove_fecha_regreso_viaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarioviaje',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='horarioviaje',
            name='origen',
        ),
        migrations.AddField(
            model_name='horarioviaje',
            name='salida',
            field=models.CharField(default='', max_length=200, verbose_name='Salida'),
        ),
    ]
