# Generated by Django 4.2.29 on 2026-04-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0013_horario_salida_sin_destino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarioviaje',
            name='cupos_totales',
        ),
        migrations.AlterField(
            model_name='horarioviaje',
            name='salida',
            field=models.CharField(max_length=200, verbose_name='Salida'),
        ),
    ]
