# Generated by Django 4.2.29 on 2026-04-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0014_remove_cupos_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='precio_vuelta',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Precio Solo Vuelta (CLP)'),
        ),
    ]
