# Generated by Django 4.2.29 on 2026-04-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0015_add_precio_vuelta_to_viaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='grupo_compra',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
