# Generated by Django 4.2.29 on 2026-04-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0016_add_grupo_compra_to_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioviaje',
            name='ciudad',
            field=models.CharField(choices=[('BELLOTO', 'Belloto'), ('VIÑA DEL MAR', 'Viña del Mar'), ('VALPARAÍSO', 'Valparaíso'), ('PLACILLA', 'Placilla'), ('CASABLANCA', 'Casablanca')], default='BELLOTO', max_length=20, verbose_name='Ciudad'),
        ),
    ]
