# Generated by Django 4.2.29 on 2026-04-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0017_horarioviaje_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='nombre_titular',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Nombre del titular'),
        ),
        migrations.AlterField(
            model_name='horarioviaje',
            name='ciudad',
            field=models.CharField(choices=[('BELLOTO', 'BELLOTO'), ('VIÑA DEL MAR', 'VIÑA DEL MAR'), ('VALPARAÍSO', 'VALPARAÍSO'), ('PLACILLA', 'PLACILLA'), ('CASABLANCA', 'CASABLANCA')], default='BELLOTO', max_length=20, verbose_name='Ciudad de Recogida'),
        ),
        migrations.AlterField(
            model_name='horarioviaje',
            name='salida',
            field=models.CharField(max_length=200, verbose_name='Paradero de Recogida'),
        ),
    ]
