# Generated by Django 4.2.29 on 2026-04-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0018_add_nombre_titular_to_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='ciudad_vuelta',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad de retorno'),
        ),
    ]
