# Generated by Django 4.2.29 on 2026-04-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0019_add_ciudad_vuelta_to_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='contacto',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Contacto'),
        ),
    ]
