# Generated by Django 4.2.29 on 2026-04-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0020_add_contacto_to_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo electrónico'),
        ),
    ]
