# Generated by Django 4.2.29 on 2026-04-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0021_add_email_to_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='rut',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='RUT del titular'),
        ),
    ]
