# Generated by Django 4.2.29 on 2026-04-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0022_add_rut_to_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='pago',
            field=models.CharField(blank=True, choices=[('WEB', 'Web')], max_length=20, null=True, verbose_name='Pago'),
        ),
    ]
