# Generated by Django 4.2.29 on 2026-04-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0023_add_pago_to_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='plataforma',
            field=models.CharField(blank=True, choices=[('PAGINA', 'Página Web'), ('WHATSAPP', 'WhatsApp'), ('INSTAGRAM', 'Instagram'), ('PRESENCIAL', 'Presencial')], max_length=20, null=True, verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pago',
            field=models.CharField(blank=True, choices=[('WEB', 'Web'), ('TRANSFERENCIA', 'Transferencia')], max_length=20, null=True, verbose_name='Pago'),
        ),
    ]
